### ISSUE TITLE
how to config 

### ISSUE THREAD

**Issue by marooj** [FuzzyHobbit/bustabit-gameserver#5]
how to config smtp address or admin page ?

**Comment by marooj** [comment]
i am installed bustabit-webserver and bustabit-gameserver and bustabit-depositor but when i click on the play button just show me game loading....

**Comment by DrDraake** [comment]
Hey Marooj,

How did you install Gameserver?  In the readme it says to...

psql -W -U moneypot -d moneypotdb -h localhost -f server/schema.sql

but in the gameserver there is no schema.sql file?  Do you go back tot he webserver directory and use that schema.sql file or just bypass that all together?

**Comment by marooj** [comment]
thank you my problem solved in bustabit-webserver you said create bustabit user and bustabitdb in bustabit-gameserver you said create user moneypot and you said create moneypotdb Although don't need. i create just bustabitdb and set ConnectionString of both of them to bustabitdb
